name: Deploy to EC2

on:
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2 using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: "ubuntu"
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/chat_bot_healthcare/
            git pull origin main
            cd chatbot_app/
            docker compose -f compose.yml up --build -d
